---

- name: PostgreSQL streaming replication pre-preflight check
  block:
    - name: ensure there is only one database in main database group
      fail:
        msg: "Multiple hosts or none in primary database group. hosts: {{ groups['database'] }}"
      when: groups['database'] | length != 1

    - name: ensure there is at least one host in replication group
      fail:
        msg: "No hosts in database_replica group"
      when: groups['database_replica'] | length == 0

    - name: ensure there are only maximum two hosts in replication group
      fail:
        msg: "Too many hosts in replica group. Only an HA and DR instance are allowed.  hosts: {{ groups['database_replica']  }}"
      when: groups['database_replica'] | length > 2

    - set_fact:
        _pgsqlrep_types: "{{ groups['database_replica'] | map('extract', hostvars, 'pgsqlrep_type') | list}}"

    - fail:
        msg: "pgsqlrep_type is undefined for one or more hosts"
      when: "'Undefined' in _pgsqlrep_types"

    - fail:
        msg: "pgsqlrep_type must be local or remote"
      when: item not in pgsqlrep_type_list
      loop: "{{ _pgsqlrep_types }}"

  delegate_to: localhost
  run_once: true

- name: set facts for master and replica. Consider using facts?
  set_fact:
    tower_replication_master_address: "{{ groups['database'][0] | infer_address(hostvars) }}"
    tower_replication_replica_address_list: "{{ groups['database_replica'] | map('infer_address', hostvars) | list }}"

- name: PostgreSQL streaming replication pre-preflight check. Contd
  block:
    - name: ensure pg_host has value of master database
      fail:
        msg: "pg_host does not match master"
      when: pg_host != tower_replication_master_address
  delegate_to: localhost
  run_once: true