---

- name: obtain secret key from primary cluster
  hosts: localhost
  gather_facts: no
  become: false
  vars:
    tower_backup_file: tower-backup-latest.tar.gz
  vars_files: tower-vars.yml
  tasks:

  - name: only run when using DR
    block:

    - name: point inventory to primary site
      include_role:
        name: tower_inventory
      vars:
        tower_inventory_file_var: tower_inventory_pm

    - name: obtain secret key
      include_role:
        name: tower_secret_key
      vars:
        tower_secret_key_delegate: "{{ groups['tower'][0] }}"

    when: tower_inventory_dr is defined 

- name: setup inventory ensuring dr/secondary site and deploy key to DR
  hosts: localhost
  gather_facts: no
  vars_files: tower-vars.yml
  tasks:

  - name: only run when using DR
    block: 

    - name: point to to DR inventory
      include_role:
        name: tower_inventory
      vars:
        tower_inventory_file_var: tower_inventory_dr

    when: tower_inventory_dr is defined

- hosts: tower
  gather_facts: no
  become: true
  tasks:

  - name: only run when using DR
    block:
    
    - name: ensure tower configuration
      file:
        state: directory
        path: /etc/tower
        mode: 0750

    - name: deploy secret to tower
      copy:
        content: "{{hostvars['localhost'].tower_secret_key}}"
        dest: "/etc/tower/SECRET_KEY"
        mode: 0750

    # adding this because installer fails this was left behind
    # and awx user and group was removed
    - name: remove extraneous tower log directory
      file:
        path: /var/log/tower
        state: absent

    when: tower_inventory_dr is defined

- name: setup inventory to configure replication
  hosts: localhost
  gather_facts: no
  vars_files: tower-vars.yml
  tasks:
  - include_role:
      name: tower_inventory
    vars:
      tower_inventory_file_var: tower_inventory_pm

- import_playbook: tower-setup-replication.yml

- import_playbook: tower-check-replication.yml
