---

- hosts: all
  gather_facts: no
  become: true
  vars:
    pkgs_to_remove:
    - ansible-tower*
    - rabbitmq-server*
    - postgresql96*
    dep_pkgs_to_remove:
    - ansible
    - python2-jmespath
    - apr
    - apr-util
    - bubblewrap
    - erlang
    - gd
    - git
    - gperftools-libs
    - libXpm
    - libgnome-keyring
    - libsemanage-python
    - libunwind
    - memcached
    - mercurial
    - neon
    - nginx*
    - pakchois
    - perl-Error
    - perl-Git
    - perl-TermReadKey
    - postgresql96
    - python-devel
    - python-meld3
    - python-virtualenv
    - rabbitmq-server
    - socat
    - subversion
    - subversion-libs
    - supervisor
    - postgresql96-libs
    - python-psycopg2
    - setools-libs
    dirs_to_remove:
    - /var/lib/pgsql
    - /var/lib/awx
    - /var/lib/rabbitmq
    - /etc/tower
    - /var/log/tower
    - /etc/yum.repos.d/ansible-tower.repo

  tasks:
  - name: ensure tower services are stopped
    command: ansible-tower-service stop
    ignore_errors: yes

  - name: remove packages
    yum:
      name: "{{ pkgs_to_remove }}"
      state: absent

  - name: remove dep packages
    yum:
      name: "{{ dep_pkgs_to_remove }}"
      state: absent
    when: uninstall_deps | default(false)

  - name: remove dirs
    file:
      path: "{{ item }}"
      state: absent
    with_items: "{{ dirs_to_remove }}"

  - name: clean yum cache
    command: "{{ item }}"
    with_items:
    - "yum clean all"
    - "rm -rf /var/cache/yum"


# Review Support article for more information https://access.redhat.com/solutions/3107181