---

- hosts: localhost
  connection: local
  become: false
  vars_files: tower-vars.yml
  tasks:

  - name: check installer already exists for offline install
    stat:
      path: "{{ tower_installer_dir }}/{{ tower_artifact }}"
    register: artifact_status

  - name: fail if installer not found
    fail:
      msg: "Installer archive not found at {{ tower_installer_dir }}/{{ tower_artifact }}"
    when: not artifact_status.stat.exists

  # - name: extract installer
  #   command: "tar xzf {{ tower_artifact }}"
  #   args:
  #     chdir: "{{ tower_installer_dir }}"
  #     creates: "{{ tower_installer_current }}"

  # vissues with running on macos with unarchive module
  - unarchive:
      src: "{{ tower_installer_dir }}/{{ tower_artifact }}"
      dest: "{{ tower_installer_dir }}/"
      remote_src: yes
      creates: "{{ tower_installer_current }}"

  - name: ensure inventory is pointed to primary
    include_role:
      name: tower_inventory
    vars:
      tower_inventory_file: "{{ tower_inventory_pm }}"

  - include_role:
      name: tower_install
    vars:
      tower_install_inventory: "{{ ansible_inventory_sources[0] }}"
      tower_install_directory: "{{ tower_installer_current }}"

