---

- hosts: localhost
  connection: local
  vars_files: vars_tower.yml
  tasks:
  - copy:
      content: "{{tower_inventory_pm}}"
      dest: .tower_inventory.ini
  - debug: msg="{{ groups }}"
  - copy:
      content: "{{tower_inventory_dr}}"
      dest: .tower_inventory.ini
  - meta: refresh_inventory
  - debug: msg="{{ groups }}"
