---

- name: setup inventory for primary site or ha site in failback)
  hosts: localhost
  vars_files: vars_tower.yml
  tasks:
  - include_role:
      name: tower_inventory
    vars:
      tower_inventory_file: "{{ tower_inventory_pm if tower_failback is not defined else tower_inventory_ha  }}"

- import_playbook: tower_stop_services.yml

- name: Set fact to indicate remove failover. Required b.c using playbook import
  hosts: database_replica
  tasks:
  - set_fact:
      promotion_type: "local"

- import_playbook: tower_pgsql_promote.yml

- name: setup inventory for ha site or primary site in failback and rerun tower installer
  hosts: localhost
  vars_files: vars_tower.yml
  tasks:
  - include_role:
      name: tower_inventory
    vars:
      tower_inventory_file: "{{ tower_inventory_ha if tower_failback is not defined else tower_inventory_pm  }}"

  - name: "run tower installer for version {{ tower_version }} LOG: {{ tower_installer_current }}/setup.log"
    command: "./setup.sh -i {{ playbook_dir }}/{{ tower_inventory_ha if tower_failback is not defined else tower_inventory_pm  }} -e required_ram=0"
    args:
      chdir: "{{ tower_installer_current }}"
    environment:
      ANSIBLE_SUDO: True
    register: tower_install_status
    ignore_errors: yes
    when: not tower_install_skip | default(false) | bool and
          not tower_install_test | default(false) | bool

  - name: fail with message
    fail:
      msg: "Tower installation failed.  Please check {{ tower_installer_current }}/setup.log"
    when: "'skipped' not in tower_install_status and tower_install_status.failed"

- name: test/engineering db update
  hosts: tower
  become: true
  roles:
  - role: tower_db_active
    when: tower_install_test | default(false) | bool

- import_playbook: tower_deprovision.yml

- import_playbook: tower_setup_replication.yml

- import_playbook: tower_check_replication.yml
