- name: Get PGSQL version 10.x
  command: "{{ pgsqlrep_bash }} psql --version"
  become: true
  become_user: postgres
  changed_when: no
  check_mode: no
  register: pgsql_version_check

- name: Set PGSQL version

  set_fact:
    pgsql_version: "{{ _base_version3 }}"
  vars:
    _example_version_str: psql (PostgreSQL) 10.6
    _base_version1: "{{ pgsql_version_check.stdout.split()[-1] }}"
    _base_version2: "{{ _base_version1.split('.') }}"
    _base_version3: "{{ '.'.join(_base_version2[0:2]) }}"

  