---
# @author Anthony Loukinas <anthony.loukinas@redhat.com>

- block:
  - name: Generate servert.crt and server.key
    shell: |
      openssl req -new -x509 -days 365 -nodes -text -out {{ pgsqlrep_data_path }}/server.crt \ 
      -keyout {{ pgsqlrep_data_path }}/server.key -subj "/CN={{ ansible_fqdn }}"

  - name: Ensure proper file permissions
    file:
      path: "{{ pgsqlrep_data_path }}/{{ item }}"
      owner: postgres
      group: postgres
      mode: '0600'
    with_items:
      - server.crt
      - server.key
  when: postgres_ssl_create

- name: Copy certificate and key
  copy:
    src: "{{ item }}"
    dest: "{{ pgsqlrep_data_path }}/{{ item }}"
    owner: postgres
    group: postgres
    mode: '0600'
  with_items:
    - server.crt
    - server.key
  when: not postgres_ssl_create

- name: Turn SSL on in PostgreSQL config
  lineinfile:
    path: "{{ pgsqlrep_data_path }}/postgresql.conf"
    line: "ssl = on"
    backup: yes

# On replica nodes, the pg_hba.conf looks like "hostsslssl" for some reason.
- name: Force ssl in pg_hba.conf
  replace:
    path: "{{ pgsqlrep_data_path }}/pg_hba.conf"
    regexp: '^host'
    replace: 'hostssl'
  # notify: restart postgresql
