---

- hosts: all
  gather_facts: no
  become: true
  tasks:
  - name: subscribe
    redhat_subscription:
      state: present
      username: "{{ rhsm_username }}"
      password: "{{ rhsm_password }}"
      auto_attach: true
      #force_register: true

  - name: install
    yum:
      name: rsync
      state: present
