---

- hosts: all
  become: true
  tasks:
  - lineinfile: path=/etc/ssh/sshd_config regexp='^PasswordAuthentication' line='PasswordAuthentication yes'
  - service: name=sshd state=restarted
  - user: name=vagrant password="{{ 'password' | password_hash('sha512', 'saltthis') }}" group=wheel
