---

- uri:
    method: "{{ tower_api_method }}"
    user: "{{ tower_api_user }}"
    password: "{{ tower_api_password }}"
    validate_certs: "{{ tower_api_validate_certs }}"
    status_code: "{{ tower_api_status_codes }}"
    force_basic_auth: "{{ tower_api_basic_auth }}"
    url: "{{ tower_api_base }}/{{ tower_api_endpoint }}"
  register: tower_api_results

- set_fact:
    "{{ tower_api_return_var }}": "{{ tower_api_results.json.results }}"

- debug:
    msg: "{{ lookup('vars', tower_api_return_var) }}"
    verbosity: 2