---

- name: delegate everything to localhost
  delegate_to: localhost
  block:

  - name: ensure vars are passed
    assert:
      that: 
        - tower_inventory_file_var is defined
      msg: tower_inventory_file_var must be passed

  - set_fact:
      tower_environment_def: "{{ lookup('vars', tower_environment_defs_var, default=false) }}"

  - name: ensure environment definitions are present
    assert:
      that: tower_environment_def
      msg: "No tower environments found in expected var: {{ tower_environment_defs_var }}"

  - name: ensure requested environment exist
    assert:
      that: tower_selected_environment in tower_environment_def
      msg: "Specified environment [{{ tower_selected_environment }}] not found in {{ tower_environment_defs_var }}"

  - set_fact:
      tower_inventory_file: "{{ tower_environment_def[tower_selected_environment][tower_inventory_file_var] }}"
    
  - name: check inventory file
    stat:
      path: "{{ tower_inventory_file }}"
    register: tower_inventory_file_status

  - fail:
      msg: "{{ tower_inventory_file }} does not exist"
    when: not tower_inventory_file_status.stat.exists

  - debug:
      msg: "setting inventory to {{tower_inventory_file}}"

  - name: "populate inventory ini with {{tower_inventory_file}}"
    copy:
      content: "{{tower_inventory_file}}"
      dest: "{{ tower_inventory_ini }}"

  - name: refresh_inventory
    meta: refresh_inventory
